Repository TeflonTrout/tdi-productions, pull requests merged in 2023-05, with the labels that each got.

#24 [FEATURE/METADATA] Updated ReadMe.md file
  README.md
Labels: feature

#25 [FEATURE/CAROUSEL] Updated Carousel
  components/Carousel/Carousel.module.css
  components/Carousel/Carousel.tsx
  components/DescriptiveCard/DescriptiveCard.tsx
  components/index.ts
  pages/films/index.tsx
  pages/index.tsx
  types/index.ts
Labels: feature

#28 [ISSUE/DESIGN/CONTACT] Fix /contact design
  components/Footer/Footer.module.css
  components/Footer/Footer.tsx
  package-lock.json
  package.json
  pages/contact/Contact.module.css
  pages/contact/index.tsx
Labels: issue

#29 [FEATURE/METADATA] Update app to include metadata in <head>
  .gitignore
  package.json
  pages/layout.tsx
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  public/tdiLogoTransparent.png
Labels: enhancement, feature

#30 [FEATURE/SKELETONS] Add skeleton loaders to images
  components/AvatarCard/AvatarCard.module.css
  components/AvatarCard/AvatarCard.tsx
  components/DescriptiveCard/DescriptiveCard.module.css
  components/DescriptiveCard/DescriptiveCard.tsx
  components/SimpleCard/SimpleCard.module.css
  components/SimpleCard/SimpleCard.tsx
  package-lock.json
  package.json
  pages/index.tsx
Labels: enhancement, feature
